# Generated by Django 5.2.7 on 2025-11-02 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('farming_tips', 'Farming Tips'), ('disease_alerts', 'Disease Alerts'), ('market_news', 'Market News'), ('weather_alerts', 'Weather Alerts'), ('government_schemes', 'Government Schemes'), ('general', 'General News')], default='general', max_length=50)),
                ('language', models.CharField(choices=[('en', 'English'), ('tw', 'Twi'), ('ak', 'Akan'), ('ew', 'Ewe'), ('ga', 'Ga'), ('dag', 'Dagbani')], default='en', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='expert_news/images/')),
                ('audio_message', models.FileField(blank=True, null=True, upload_to='expert_news/audio/')),
                ('audio_duration', models.IntegerField(default=0, help_text='Audio duration in seconds')),
                ('is_urgent', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('target_regions', models.CharField(blank=True, help_text='Comma-separated regions', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expert', models.ForeignKey(limit_choices_to={'is_approved': True, 'user_type': 'expert'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Expert News',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('saved', models.BooleanField(default=False)),
                ('listened', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_news.expertnews')),
            ],
            options={
                'unique_together': {('farmer', 'news')},
            },
        ),
    ]
