# Generated by Django 5.2.7 on 2025-10-24 18:37

import disease_reports.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('crop_type', models.CharField(choices=[('maize', 'Maize'), ('cassava', 'Cassava'), ('yam', 'Yam'), ('plantain', 'Plantain'), ('tomato', 'Tomato'), ('pepper', 'Pepper'), ('cocoa', 'Cocoa'), ('coffee', 'Coffee'), ('livestock', 'Livestock'), ('poultry', 'Poultry'), ('other', 'Other')], max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=disease_reports.models.disease_image_upload_path)),
                ('audio_note', models.FileField(blank=True, null=True, upload_to=disease_reports.models.audio_upload_path)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disease Report',
                'verbose_name_plural': 'Disease Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpertRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField()),
                ('treatment_plan', models.TextField()),
                ('preventive_measures', models.TextField(blank=True)),
                ('audio_response', models.FileField(blank=True, null=True, upload_to=disease_reports.models.audio_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disease_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='disease_reports.diseasereport')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expert Recommendation',
                'verbose_name_plural': 'Expert Recommendations',
                'ordering': ['-created_at'],
            },
        ),
    ]
