# Generated by Django 5.2.7 on 2025-10-31 15:36

import disease_reports.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=disease_reports.models.disease_image_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('disease_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='disease_reports.diseasereport')),
            ],
            options={
                'verbose_name': 'Disease Report Image',
                'verbose_name_plural': 'Disease Report Images',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
