# Generated by Django 5.2.7 on 2025-11-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease_reports', '0002_diseasereportimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseasereport',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='diseasereport',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
