# Generated by Django 5.2.7 on 2025-10-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
